In [1]:
import pandas as pd
import numpy as np
import ast
import nltk

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem.porter import PorterStemmer

DATA MERGING AND PRE-PROCESSING

In [3]:
#DOWNLOAD DATASET
A=pd.read_csv("tmdb_5000_movies.csv")
A

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
B=pd.read_csv("tmdb_5000_credits.csv")
B

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [5]:
#MERGE DATASETS ON THE'title' COLUMN
A=A.merge(B,on='title')
A

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [6]:
A.shape

(4809, 23)

In [7]:
A['title'].nunique()

4800

In [8]:
A['title'].unique()

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4800,), dtype=object)

In [9]:
A['movie_id'].nunique()

4803

In [10]:
A['title'].value_counts()

title
The Host                 4
Batman                   4
Out of the Blue          4
Avatar                   1
The Girl on the Train    1
                        ..
Step Up 3D               1
Secondhand Lions         1
The Age of Adaline       1
Drag Me to Hell          1
My Date with Drew        1
Name: count, Length: 4800, dtype: int64

In [11]:
#)SELECTING CORE COLUMNS
A=A[['movie_id','title','genres','keywords','cast','crew']]

In [12]:
#)CLEAN DICTIONARIES TO EXTRACT TEXT LISTS
obj = "[{'name': 'movie_id'}, {'name': 'title'}, {'name': 'genres'},{'name': 'keywords'}, {'name': 'cast'}, {'name': 'crews'}]"

In [13]:
def convert_json_to_list(obj):
    """Helper function to extract names from genres and keywords JSON strings."""
    name_list = []
    for i in ast.literal_eval(obj):
        name_list.append(i['name'])
    return name_list

In [14]:
def convert_cast(obj):
    """Helper function to extract the top 3 actors from the cast."""
    cast_list=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
             cast_list.append(i['name'])
             counter +=1
        else:
           break
    return cast_list

In [15]:
def fetch_director(obj):
    """Helper function to extract the director's name from the crew."""
    director_list=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            
            director_list.append(i['name'])
            break
    return cast_list

In [16]:
def safe_convert_json_to_list(data):
    if isinstance(data, list):  
        return data
    if isinstance(data, str):   
        try:
            return convert_json_to_list(data)
        except:
            return []  
    return []  

def safe_convert_json_to_cast(data):
    if isinstance(data, list):  
        return data
    if isinstance(data, str):   
        try:
            return convert_json_to_cast(data)
        except:
            return []
    return []

def safe_fetch_director(data):
    if isinstance(data, list):  
        return data
    if isinstance(data, str):   
        try:
            return fetch_director(data)
        except:
            return []
    return []

#)Applying the parsing transformations
A['genres'] = A['genres'].apply(safe_convert_json_to_list)
A['keywords'] = A['keywords'].apply(safe_convert_json_to_list)
A['cast'] = A['cast'].apply(safe_convert_json_to_cast)
A['crew'] = A['crew'].apply(safe_fetch_director)

C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\88420156.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['genres'] = A['genres'].apply(safe_convert_json_to_list)
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\88420156.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['keywords'] = A['keywords'].apply(safe_convert_json_to_list)
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\88420156.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['cast'] = A['cast'].apply(safe_convert_json_to_cast)
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\88420156.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['crew'] = A['crew'].apply(safe_fetch_director)

In [17]:
#Removing spaces within words/names to ensure entities 
A['genres']=A['genres'].apply(lambda x:[i.replace(" ","") for i in x])
A['keywords']=A['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
A['cast']=A['cast'].apply(lambda x:[i.replace(" ","") for i in x])
A['crew']=A['crew'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\543786411.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['genres']=A['genres'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\543786411.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['keywords']=A['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\543786411.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['cast']=A['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\543786411.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['crew']=A['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [19]:
#)CREATING THE FINAL STRING COLUMN:'tags' BY COMBINING GENRES,KEYWORDS,CAST,CREW COLUNMS
A['tags']=A['genres']+A['keywords']+A['cast']+A['crew']

C:\Users\vandana v\AppData\Local\Temp\ipykernel_55136\272248675.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['tags']=A['genres']+A['keywords']+A['cast']+A['crew']

In [32]:
#)Creating a clean Dataframe with only the necessary deployment of columns
C=A[['movie_id','title','tags']].copy()
C

,movie_id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4805,72766,Newlyweds,"[Comedy, Romance]"
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4807,126186,Shanghai Calling,[]
4808,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [21]:
C.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   tags      4809 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.8+ KB

In [43]:
#)Cleaning up the tags column & forcing everythingsafely into the strings
C['tags']=C['tags'].fillna('').astype(str)
C['tags']

0            ['action',
1         ['adventure',
2            ['action',
3            ['action',
4            ['action',
             ...
4804         ['action',
4805         ['comedy',
4806         ['comedy',
4807                 []
4808    ['documentary',
Name: tags, Length: 4809, dtype: object

In [44]:
#)Re-verifying lowercase conversion safely
C['tags']=C['tags'].apply(lambda x: x.lower() if isinstance(x,str)else"")
C['tags']

0            ['action',
1         ['adventure',
2            ['action',
3            ['action',
4            ['action',
             ...
4804         ['action',
4805         ['comedy',
4806         ['comedy',
4807                 []
4808    ['documentary',
Name: tags, Length: 4809, dtype: object

VECTORIZATION  AND  MAIN LOGIC

In [26]:
import nltk
from nltk.stem.porter import PorterStemmer

In [27]:
#APPLYING STEMMING TO THE tag TEXT
ps=PorterStemmer()

In [28]:
def stem_text(text):
    stemmed_words=[]
    for word in text.split():
        stemmed_words.append(ps.stem(word))
        return" ".join(stemmed_words)

In [41]:
C['tags']=C['tags'].apply(stem_text)
C['tags']

0            ['action',
1         ['adventure',
2            ['action',
3            ['action',
4            ['action',
             ...
4804         ['action',
4805         ['comedy',
4806         ['comedy',
4807                 []
4808    ['documentary',
Name: tags, Length: 4809, dtype: object

In [38]:
#COUNT VECTORIZATION
#)Convert text tags into numerical coordinates using max 5000 frequent terms(excluding stop words)
cv = CountVectorizer(max_features=5000,stop_words='english')
cv

CountVectorizer(max_features=5000, stop_words='english')

In [39]:
#)CONVERT WORDS TO MATRIX COLUMNS
vector_matrix=cv.fit_transform(C['tags']).toarray()
vector_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4809, 5000))

In [40]:
#)COSINE SIMILARITY MATRIX
similarity = cosine_similarity(vector_matrix)
similarity

array([[1.        , 0.13416408, 0.12649111, ..., 0.06666667, 0.        ,
        0.        ],
       [0.13416408, 1.        , 0.14142136, ..., 0.        , 0.        ,
        0.        ],
       [0.12649111, 0.14142136, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06666667, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(4809, 4809))

RECOMMENDATION FUNCTION

In [45]:
#)WRITING THE RECOMMENDATION FUNCTION
def recommend(movie_title):
    try:
        movie_index = C[C['title'].str.lower() == movie_title.lower()].index[0]
        distance=similarity[movie_index]
        movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x: x[1])[1:6]
        print (f"\nTop 5 reccomendations for '{movie_title}':")
        print("-" * 40)
        for rank,item in enumerate(movie_list,1):
            recommended_movie_index=item[0]
            print(f"{rank}.{C.iloc[recommended_movie_index]
                ['title']}")
    except IndexError:
                 print(f"Error:'{movie_title}' was not found in the dataset .Please check your spelling.")

In [46]:
#)EXECUTION EXAMPLE
recommend('Avatar')

Top 5 reccomendations for 'Avatar':
----------------------------------------
1.Star Trek Into Darkness
2.The Lovers
3.Jupiter Ascending
4.The Time Machine
5.The Mummy: Tomb of the Dragon Emperor

ABOUT THE PROJECT:
     This project builds a 'CONTENT-BASED MOVIE RECOMMENDATION SYSTEM'.
Instead of recommending movies based on what other people liked(collabarative filtering),this system looks at the actual content attributes
of a movie you like.When a user inputs a movie title ,the system calculates text similarity scores across a combined "metadata profile "(genres,keywords,directors & cast) and instantly recommends the top 5 closest matching movies.

The core workflow:
1.Data merging:Combines the TMDB 5000 movies dataset with the credits dataset on the movie title.
2.Feature extraction:Cleans complex stringified JSON columns to pull out raw list names(like specific genre names & actor names).
3.Tag creation:Merges all descriptive  columns into one gaint text block per movie called tags.
4.Natural language processing(NLP):*Stemming:trims words down to their root forms(e.g.,coverting"loving" or "loved" into"love")so the computer counts them as the same concept.
a)Vectorization:Converts those text tags into multiple-dimensional numerical coordinates.
5.Similarity calculation:Computes the geometric angle between movie vectors using Cosine similarity to construct a massive correlation matrix.

Libraries used:
The project relies on the core python data science & machine learning ecosystem:
1.Pandas:Used for data manipulation,loading the csv datasets,merging dataframes ,handling missing values & engineering the tags column.
2.NumPy:Used for fast numerical operations behind the scenes & transforming matix arrays.
3.ast(Abstract syntax trees):Crucial for evaluating stringified lists inside the raw dataset(ast,literal_eval),allowing to safely convert     text data into real python dictionaries & lists.
4.NLTK(Natural language toolkit):Specifically utilizes the PorterStemmer class to standardize text & strip word suffixes before vectorizing.
5.Scikit-learn(sklearn):
a) CounterVectorizer:Converts the text tags column into a spacrse matrix of word token counts(ignoring common english stop words)
b)Cosine_similarity:Computes the cosine distance matrix between all movie rows.



* BUSINESS INSIGHTS:
   We can analyze a Content-based recommendation system through a bussiness lens based on commercial value ,user retention and platform growth.
The key business insights:
(1).Core business value propositions:
(a)Overcoming the"Cold start" problem for new items:
   In traditional collaborative filtering systems(like those used by Netflix or Amazon),a brand-new movie cannot be recommended to anyone until hundreds of people have already watched and rated it.Because system relies entirely on the movie's content,a newly released film can be recommended to the perfect audience instantly on day one.
(b)Hyper-personalization and Long-tail discovery:
   Many platforms suffer from"blockbluster bias" where only the top 1% of popular movies get recommended.A content-based engine surfaces niche,lesser-known indie films (the "long-tail" inventory) simply because their attributes match a user's taste profile.This maximizes the commercial utility entire movie catalog.
(c)Increased user engagement and session length:By serving accurate,automated"What to watch next" recommendations,you reduce user decision fatigue.Keeping a user engaged on a streaming platform for just 10 or 15 minutes longer directly drives subscription renewals and ad-revenue metrics.
(2).Key performance indicators(KPIs) to track:
   If this system were deployed in a real-word application,its bussiness success would be measured using these specific metrics like:Click-through rate(CTR),Conversion rate,Catalog coverage,Churn reduction.
(3).Strategic recommendations for next-gen upgrades:
   To scale upto into a multi-million dollar business asset,a company would implement the following  strategic steps:
(a)Incorporate temporal context:Real-world behavior changes based on time(e.g, users want different genres on a Friday night vs Tuesday morning).Incorporating time-stamped metadata dynamically changes vector calculations.
(b)Monetization weighting:In commercial systems,the sorting mechanismm isn't just based on geometric similarity.It is slightly weighted by business priorities,such as high-margin content,trending titles or sponsored movie promotions.
(c)Transition to a hybrid system:While content filtering is perfect for understanding the item ,combining it with real user behavioral loops(e.g,Implicit feedback like watch history and explicitly skipping a movie) yields the gold standard of modern industry recommendation engines.


Final verdict:
This is an end-to-end implementation of a text-based search pipeline.
1.Efficient NLP pipeline:Using a text-cleaning step followed by stemming ensures that the dimensionality of vector space is highly optimized,keeping memory usage minimal while maximizing recommendation relevance.
2.Clean API:The final recommend() function  effectively acts as an operational micro-service inside the notebook.It abstracts away the complex matrix calculations,error-proofs inputs against improper case capitalization,handles unknown film titles gracefully & quickly serves up user recommendations.
3.Processing:By merging the director & cast names into single tokens ,vectorizer successfully avoids getting confused by common first names & focuses strictly on unique individuals.

This project stands out as a solid foundation in Natural language processing and is fully ready to be integrated into an application backend or showcased on a portfolio.